[book]
authors = ["古明地觉"]
language = "zh-cn"
multilingual = false
src = "src"
title = "CPython3.8 源码探秘"

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/satori1995/cpython-internal"
site-url = "/cpython-internal/"

fold.enable = false
toc = { enable = true, levels = [2, 3] }
copy-fonts = true
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]

[output.latex]
latex = true
pdf = false
